# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://akashpalrecha.github.io/memory_net/"

git_url = "https://github.com/akashpalrecha/memory_net/tree/master/"

def custom_doc_links(name): return None
